FROM nginx:1.15.11-alpine

WORKDIR /proxless

RUN apk update && apk add --no-cache apache2-utils gettext

ENV BACKEND_HOST="http://hello-proxless"

COPY nginx.conf .

# support running as arbitrary user which belogs to the root group
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
RUN chgrp -R root /var/cache/nginx

RUN addgroup nginx root
USER nginx

ENTRYPOINT [ "sh", "-c" ]

CMD [ "envsubst < /proxless/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g \"daemon off;\"" ]