{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "proxless.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ toYaml .Values.ingress.annotations}}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secret }}
      hosts:
        - {{ .Values.ingress.host}}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - backend:
              serviceName: {{ template "proxless.fullname" . }}
              servicePort: {{ .Values.port }}
{{- end }}