apiVersion: v1
kind: Service
metadata:
  name: {{ template "proxless.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ template "proxless.fullname" . }}
  type: "{{ .Values.service.type }}"