apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"