# Default values for proxless.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bappr/proxless
  tag: latest
  pullPolicy: Always

logLevel: DEBUG
port: 80

## If true, a Role will be created - Proxless is only working within the namespace
## If false, a ClusterRole will be created - Proxless is available globally
namespaceScoped: true

env:
  MAX_CONS_PER_HOST: 10000
  SERVERLESS_TTL_SECONDS: 30 # Time in seconds proxless waits before scaling down the app
  DEPLOYMENT_READINESS_TIMEOUT_SECONDS: 30 # Time in seconds proxless waits for the deployment to be ready when scaling up the app

service:
  type: "ClusterIP"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    enabled: false
    secret: proxless-tls
  host: proxless.kintohub.net