# Default values for proxless.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bappr/proxless
  tag: latest
  pullPolicy: IfNotPresent

logLevel: DEBUG
port: 8080

## If true, a Role will be created - Proxless is only working within the namespace
## If false, a ClusterRole will be created - Proxless is available globally
namespaceScoped: false

replicas: 2

env:
  MAX_CONS_PER_HOST: 10000
  SERVERLESS_TTL_SECONDS: 30 # Time in seconds proxless waits before scaling down the app
  DEPLOYMENT_READINESS_TIMEOUT_SECONDS: 30 # Time in seconds proxless waits for the deployment to be ready when scaling up the app
  REDIS_URL: proxless-redis-master:6379 # configured to use redis below

service:
  type: "ClusterIP"

nodeSelector: {}

tolerations: []

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 256Mi
  requests: {}
  #   cpu: 250m
  #   memory: 256Mi

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    enabled: false
    secret: proxless-tls
  host: proxless.kintohub.net


#######
# Values for redis
#######
redis:
  enabled: true
  cluster:
    enabled: false
  usePassword: false
  master:
    persistence:
      enabled: false
  securityContext:
    enabled: false