apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
    proxless-service: example
    proxless-enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      proxless-service: example
  template:
    metadata:
      labels:
        proxless-service: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    proxless/domain-name: "www.example.io,example.io"
    proxless/service-name: "example"
    proxless/service-port: "80"
  name: example-proxless
  labels:
    proxless-service: example
spec:
  ports:
  - port: 80
  type: ClusterIP