apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: main
          image: tutum/hello-world
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    proxless/domains: "hello-world.proxless.kintohub.net" ## domains names proxless will be able to proxy
    proxless/deployment: "hello-world" ## name of the deployment proxless will scale up and down
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hello-world.proxless.kintohub.net
      http:
        paths:
          - backend:
              serviceName: proxless # name of the proxless service
              servicePort: 8080 # port of the proxless service