apiVersion: v1
kind: DeploymentConfig
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: backend
    track: stable
  replicas: 0
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "openshift/hello-openshift"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  annotations:
    proxless/deployment: "hello"
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: hello
    tier: frontend
    track: stable
  replicas: 0
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "bappr/proxless-nginx-example:openshift"
          env:
            - name: BACKEND_HOST
              value: "http://hello-proxless:8080"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    proxless/domains: "example.io,www.example.io"
    proxless/deployment: "frontend"
    proxless/ttl-seconds: "120"
    proxless/readiness-timeout-seconds: "30"
spec:
  selector:
    app: hello
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080