name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t proxless:latest .
